-- Seed minimo de materia-prima para a base inicial real do SAFISA.
USE safisa;

DELETE FROM materia_prima_fornecedor;
DELETE FROM materias_primas;

INSERT INTO materias_primas (
  id,
  codigo,
  nome,
  categoria,
  material,
  liga,
  geometria,
  bitola,
  bitola_mm,
  comprimento_padrao_mm,
  peso_por_metro,
  peso_unitario_kg,
  densidade_g_cm3,
  estoque_minimo,
  unidade_estoque,
  id_fornecedor_principal,
  observacao
) VALUES
  (
    1,
    'MP-GENERICA',
    'MATERIA-PRIMA GENERICA',
    'LAMINADO',
    'NA',
    'NA',
    'NA',
    'NA',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0.000,
    'KG',
    9,
    'Registro generico legado para pecas produzidas ainda nao mapeadas.'
  ),
  (
    2,
    '250FD',
    'CORPO CJ--015',
    'FUNDIDO',
    NULL,
    'FERRO FUNDIDO',
    'FUNDIDO',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    7.2000,
    0.000,
    'UN',
    6,
    'Materia-prima fundida.'
  ),
  (
    3,
    '300FD',
    'CORPO MBF-040',
    'FUNDIDO',
    NULL,
    'FERRO FUNDIDO',
    'FUNDIDO',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    7.2000,
    0.000,
    'UN',
    6,
    'Materia-prima fundida.'
  ),
  (
    4,
    '350FD',
    'CORPO BR-040',
    'FUNDIDO',
    NULL,
    'FERRO FUNDIDO',
    'FUNDIDO',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    7.2000,
    0.000,
    'UN',
    6,
    'Materia-prima fundida.'
  ),
  (
    5,
    '355FD',
    'CORPO PRINCIPAL DO BR-040 C/ FURACAO',
    'FUNDIDO',
    NULL,
    'FERRO FUNDIDO',
    'FUNDIDO',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    7.2000,
    0.000,
    'UN',
    6,
    'Materia-prima fundida.'
  ),
  (
    6,
    '400FD',
    'CORPO DO VF',
    'FUNDIDO',
    NULL,
    'FERRO FUNDIDO',
    'FUNDIDO',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    7.2000,
    0.000,
    'UN',
    6,
    'Materia-prima fundida.'
  ),
  (
    7,
    '401FD',
    'CORPO MC-040',
    'FUNDIDO',
    NULL,
    'FERRO FUNDIDO',
    'FUNDIDO',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    7.2000,
    0.000,
    'UN',
    6,
    'Materia-prima fundida.'
  ),
  (
    8,
    '450FD',
    'CORPO DO MBF-032',
    'FUNDIDO',
    NULL,
    'FERRO FUNDIDO',
    'FUNDIDO',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    7.2000,
    0.000,
    'UN',
    6,
    'Materia-prima fundida.'
  ),
  (
    9,
    '500FD',
    'CORPO DO TR - 100',
    'FUNDIDO',
    NULL,
    'FERRO FUNDIDO',
    'FUNDIDO',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    7.2000,
    0.000,
    'UN',
    6,
    'Materia-prima fundida.'
  );

INSERT INTO materia_prima_fornecedor (
  id_materia_prima,
  id_fornecedor,
  observacao
) VALUES
  (1, 9, 'Fornecedor principal legado para materia-prima generica'),
  (2, 6, 'Fornecedor padrao para fundidos'),
  (3, 6, 'Fornecedor padrao para fundidos'),
  (4, 6, 'Fornecedor padrao para fundidos'),
  (5, 6, 'Fornecedor padrao para fundidos'),
  (6, 6, 'Fornecedor padrao para fundidos'),
  (7, 6, 'Fornecedor padrao para fundidos'),
  (8, 6, 'Fornecedor padrao para fundidos'),
  (9, 6, 'Fornecedor padrao para fundidos');

ALTER TABLE materias_primas AUTO_INCREMENT = 10;
